[2024-04-24T09:23:21.379+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: use_case_dag.task_2 manual__2024-04-24T09:23:01.223931+00:00 [queued]>
[2024-04-24T09:23:21.390+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: use_case_dag.task_2 manual__2024-04-24T09:23:01.223931+00:00 [queued]>
[2024-04-24T09:23:21.391+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-24T09:23:21.407+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): task_2> on 2024-04-24 09:23:01.223931+00:00
[2024-04-24T09:23:21.415+0000] {standard_task_runner.py:60} INFO - Started process 4428 to run task
[2024-04-24T09:23:21.420+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'use_case_dag', 'task_2', 'manual__2024-04-24T09:23:01.223931+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/use_case_dag.py', '--cfg-path', '/tmp/tmpm3_42pv6']
[2024-04-24T09:23:21.424+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask task_2
[2024-04-24T09:23:21.489+0000] {task_command.py:423} INFO - Running <TaskInstance: use_case_dag.task_2 manual__2024-04-24T09:23:01.223931+00:00 [running]> on host 426889f50441
[2024-04-24T09:23:21.598+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='matteo' AIRFLOW_CTX_DAG_ID='use_case_dag' AIRFLOW_CTX_TASK_ID='task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T09:23:01.223931+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T09:23:01.223931+00:00'
[2024-04-24T09:23:33.752+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/use_case_dag.py", line 44, in task_2
    utils.join_data(transformed_owid_covid_data, country_wise_covid, joined_data)
  File "/opt/airflow/dags/utils.py", line 102, in join_data
    joined_df.write.parquet(joined_data.kw_args['path'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
    self._jwrite.parquet(path)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_ALREADY_EXISTS] Path file:/opt/airflow/data/joined_data already exists. Set mode as "overwrite" to overwrite the existing path.
[2024-04-24T09:23:33.778+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=use_case_dag, task_id=task_2, execution_date=20240424T092301, start_date=20240424T092321, end_date=20240424T092333
[2024-04-24T09:23:33.796+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task task_2 ([PATH_ALREADY_EXISTS] Path file:/opt/airflow/data/joined_data already exists. Set mode as "overwrite" to overwrite the existing path.; 4428)
[2024-04-24T09:23:33.822+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T09:23:33.856+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
