[2024-04-24T09:13:25.650+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: use_case_dag.task_3 manual__2024-04-24T08:41:16.403808+00:00 [queued]>
[2024-04-24T09:13:25.662+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: use_case_dag.task_3 manual__2024-04-24T08:41:16.403808+00:00 [queued]>
[2024-04-24T09:13:25.662+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-04-24T09:13:25.679+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): task_3> on 2024-04-24 08:41:16.403808+00:00
[2024-04-24T09:13:25.687+0000] {standard_task_runner.py:60} INFO - Started process 3382 to run task
[2024-04-24T09:13:25.692+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'use_case_dag', 'task_3', 'manual__2024-04-24T08:41:16.403808+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/use_case_dag.py', '--cfg-path', '/tmp/tmpx7y9xaac']
[2024-04-24T09:13:25.697+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask task_3
[2024-04-24T09:13:25.766+0000] {task_command.py:423} INFO - Running <TaskInstance: use_case_dag.task_3 manual__2024-04-24T08:41:16.403808+00:00 [running]> on host 426889f50441
[2024-04-24T09:13:25.867+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='matteo' AIRFLOW_CTX_DAG_ID='use_case_dag' AIRFLOW_CTX_TASK_ID='task_3' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T08:41:16.403808+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T08:41:16.403808+00:00'
[2024-04-24T09:13:35.475+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/use_case_dag.py", line 50, in task_3
    utils.get_best_countries(joined_data, best_recovery_countries)
  File "/opt/airflow/dags/utils.py", line 102, in get_best_countries
    joined_df = spark.read.parquet(joined_data.kw_args['path'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/readwriter.py", line 544, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [UNABLE_TO_INFER_SCHEMA] Unable to infer schema for Parquet. It must be specified manually.
[2024-04-24T09:13:35.509+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=use_case_dag, task_id=task_3, execution_date=20240424T084116, start_date=20240424T091325, end_date=20240424T091335
[2024-04-24T09:13:35.531+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task task_3 ([UNABLE_TO_INFER_SCHEMA] Unable to infer schema for Parquet. It must be specified manually.; 3382)
[2024-04-24T09:13:35.581+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-24T09:13:35.608+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
